services:
  postgres:
    container_name: payment-postgres
    image: postgres:17.4-bullseye
    restart: always
    ports:
      - 5432:5432
    environment:
      TZ: CET
      PGTZ: CET
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeMe
      POSTGRES_DB: payment-db
    volumes:
      - "C:/shared/postgresql:/var/log/postgresql:ro"

# based on https://www.baeldung.com/ops/kafka-docker-setup
  zookeeper:
    container_name: payment-zookeeper
    image: confluentinc/cp-zookeeper:7.8.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    container_name: payment-kafka
    image: confluentinc/cp-kafka:7.8.2
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

# later we can use this:
#
#  kafka-ui:
#    image: provectuslabs/kafka-ui:v0.7.2
#    depends_on:
#      - kafka
#    ports:
#      - 8090:8080
#    environment:
#      KAFKA_CLUSTERS_0_NAME: local
#      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
#      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

#  payment:
#    container_name: payment-app-container
#    environment:
#      - PG_JDBC_URL=jdbc:postgresql://postgres:5432/payment-db
#      - PG_JDBC_USERNAME=postgres
#      - PG_JDBC_PASSWORD=changeMe
#      - TZ=CET
#    depends_on:
##      - kafka
#      - postgres
#    ports:
#      - 8080:8080
#    build:
#      context: .
#      dockerfile: Dockerfile

