apiVersion: apps/v1
# see https://medium.com/womenintechnology/create-a-kubernetes-cluster-using-docker-desktop-72b493f3faa8
kind: Deployment
metadata:
  name: "payment"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "payment"
  template:
    metadata:
      labels:
        app: "payment"
    spec:
      containers:
        - name: "payment"
          image: "payment-payment"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: actuator/health/liveness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: "payment"
spec:
  selector:
    app: "payment"
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8080