application:
  name: Payment
  description: Instant Payment System for Kibit assignment
  version: 1
  timezone: ${TZ:CET}
spring:
  threads:
    virtual:
      enabled: true
  liquibase:
#    contexts: local
    change-log: classpath:db/changelog/000_master.yml
    url: ${PG_JDBC_URL:jdbc:postgresql://localhost:5432/payment-db}
    user: ${PG_JDBC_USERNAME:postgres}
    password: ${PG_JDBC_PASSWORD:changeMe}
    enabled: true
  datasource:
    url: ${PG_JDBC_URL:jdbc:postgresql://localhost:5432/payment-db}
    username: ${PG_JDBC_USERNAME:postgres}
    password: ${PG_JDBC_PASSWORD:changeMe}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  output:
    ansi:
      enabled: always
  kafka:
    bootstrap-servers: localhost:29092 # payment running from container the config: kafka:9092
springdoc:
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info,configprops"
info:
  application:
    name: ${application.name}
    description: ${application.description}
    version: '@project.version@'
    release-date: 2025.03.31
    java-version: ${java.vendor} VM ${java.vendor.version}
    spring-boot-version: '@project.parent.version@'
server:
  error:
    include-message: always

