### POST request
POST http://localhost:8080/payment/api/v1/accounts/
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Lenon",
  "accountNumber": "12355899B",
  "accountType": "credit",
  "currency": "USD",
  "balance": 0
}

### return :

HTTP/1.1 200
Content-Type: application/json
Transfer-Encoding: chunked
Date: Wed, 02 Apr 2025 08:23:30 GMT

{
  "id": 1004,
  "accountNumber": "12355899B",
  "accountType": "credit",
  "currency": "USD",
  "balance": 0,
  "active": true,
  "customer": {
    "id": 5,
    "lastName": "Lenon",
    "firstName": "John",
    "address": "5th avenue 1234 NJ",
    "active": true
  }
}
