### POST request
POST http://localhost:8080/payment/api/v1/customers/
Content-Type: application/json

{
  "address": "H-1038 Karacsony Sandor u. 97. I/2",
  "firstName": "Csaba",
  "lastName": "Tenkes"
}

### return :

HTTP/1.1 200
Content-Type: application/json
Transfer-Encoding: chunked
Date: Wed, 02 Apr 2025 00:27:12 GMT

{
  "id": 1000,
  "lastName": "Tenkes",
  "firstName": "Csaba",
  "address": "H-1038 Karacsony Sandor u. 97. I/2",
  "active": true
}


### POST request
POST http://localhost:8080/payment/api/v1/customers/
Content-Type: application/json

{
  "address": "H-1038 Kiss Karoly u. 97. I/2",
  "firstName": "John",
  "lastName": "Lenon"
}

### return :

HTTP/1.1 409
Content-Type: application/json
Transfer-Encoding: chunked
Date: Wed, 02 Apr 2025 00:30:48 GMT

{
  "errorCode": "CUSTOMER_FOUND",
  "message": "With firstName: John, lastName:Lenon a customer has already existed.",
  "timestamp": "2025-04-02T02:30:48.8243932"
}
