### GET request to example server
GET http://localhost:8080/payment/api/v1/cards/12345678-12345678-12345678/balance
###
HTTP/1.1 200
Content-Type: application/json
Transfer-Encoding: chunked
Date: Tue, 01 Apr 2025 22:38:36 GMT

{
  "issueDate": "2025-04-02T00:38:36.9840176",
  "accountNumber": "12345678A",
  "balance": 550,
  "currency": "EUR"
}